require('json2ify')
require('es5-shimify')
require('jqueryify')
require('shuffle/lib')

require('spine')
require('spine/lib/local')
require('spine/lib/ajax')
require('spine/lib/manager')
require('spine/lib/route')
require('spine/lib/tmpl')
require('spine/lib/relation')
